name: Deploy to UAT

on:
  push:
    branches: [ uat ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run tests
      run: npm run test
      
    - name: Build application
      run: npm run build
      env:
        NODE_ENV: uat
        MONGODB_URI: ${{ secrets.MONGODB_URI_UAT }}
        NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET_UAT }}
        JWT_SECRET: ${{ secrets.JWT_SECRET_UAT }}
        
    - name: Deploy to Vercel (UAT)
      uses: amondnet/vercel-action@v25
      with:
        vercel-token: ${{ secrets.VERCEL_TOKEN }}
        vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
        vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID_UAT }}
        vercel-args: '--prod'
        
    - name: Run database migrations
      run: npm run db:migrate
      env:
        MONGODB_URI: ${{ secrets.MONGODB_URI_UAT }}
        
    - name: Notify deployment success
      if: success()
      uses: 8398a7/action-slack@v3
      with:
        status: success
        text: 'UAT deployment successful! 🚀'
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        
    - name: Notify deployment failure
      if: failure()
      uses: 8398a7/action-slack@v3
      with:
        status: failure
        text: 'UAT deployment failed! ❌'
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} 